from shiny.express import input, render, ui
from shiny import reactive
import pandas as pd
from pathlib import Path

print("packages imported successfully")


#put in the path to the github repo data generated by the Institutional Innovation Grapher that you would like to display in a Shiny interactive table
datasource = ""

filtercolumns = True
usecustomcss = True

#the columnstofilter will be used to drop columns from the interactive table
columnstofilter = []
columnstofilter.append('size')
columnstofilter.append('archived')
columnstofilter.append('disabled')
columnstofilter.append('watchers_count')
columnstofilter.append('open_issues_count')
columnstofilter.append('full_name')
columnstofilter.append('forks')


originaldf = pd.read_csv(datasource)

if filtercolumns:
    df = originaldf.drop(columns=columnstofilter)

print("following columns successfully dropped from df: " + str(columnstofilter))



if usecustomcss:
    css_file = Path(__file__).parent / "css" / "styles.css"
    ui.include_css(css_file)


@render.data_frame
def generatetable():
    return render.DataTable(df, filters=True)


